# -*- coding: utf-8 -*-
"""Create NetCDF Files (4).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19V5FlDNGcRPjmA83NTir74svZD98zNGs

# Define Main Functions
"""

from read_cnv_header import read_cnv_header
from parse_cnv import parse_cnv
import pandas as pd
import gsw
import numpy as np
import scipy.io as sio

def remove_spikes(dataframe):
    
    # Replace known "fake NaNs" (e.g., -9.990e-29) with real NaNs
    dataframe = dataframe.replace(-9.990e-29, np.nan)

    #columns to check for spikes
    columns_to_check = [
        "Conductivity",
        "Conservative Temp",
        "Potential Temp",
        "Oxygen",
        "Absolute Salinity",
        "Practical Salinity"]

    #parameters for spike detection
    window_size = 50 #window for defining rolling mean
    threshold = 3  #number of st devs away from mean

    #boolean mask to keep rows (start with all True)
    valid_rows = pd.Series(True, index=dataframe.index)

    for col in columns_to_check:
        series = dataframe[col]
        rolling_mean = series.rolling(window=window_size, center=True).mean()
        rolling_std = series.rolling(window=window_size, center=True).std()

        # identify where the absolute deviation from the mean exceeds threshold × std
        spike_mask = (np.abs(series - rolling_mean) > threshold * rolling_std)

        spike_mask.fillna(False) #make NaNs false (no spike)

        #valid rows are only when spike mask is false
        valid_rows &= ~spike_mask

    # Apply the mask to remove spike rows
    dataframe_cleaned = dataframe[valid_rows].reset_index(drop=True)

    return dataframe_cleaned


def make_UC_and_DC_dataframes(filename, date):

    #Parse header for variable names and other information
    cast_num, latitude, longitude, variables = read_cnv_header(filename)

    #Extract data from cnv file
    #data_cols is a dictionary with key=variable names
    #data_array is an array with each column = one variable (corresponds with index)
    data_cols, data_array= parse_cnv(filename, variables)

    #Grab individual variable data from data_cols as needed
    #Use variable name (from print statement) as key: i.e. ['timeS: Time, Elapsed [seconds]']

    pres = data_cols['prdM: Pressure, Strain Gauge [db]']
    oxy = data_cols['sbeox0ML/L: Oxygen, SBE 43 [ml/l]']
    fluor = data_cols['flECO-AFL: Fluorescence, WET Labs ECO-AFL/FL [mg/m^3]']
    turb2 = data_cols['turbWETntu1: Turbidity, WET Labs ECO, 2 [NTU]']
    cond = data_cols['c0mS/cm: Conductivity [mS/cm]']


    ##OR
    #Grab individual variable data from data_array as needed (Useful for repeat variable names)
    #Use index (from print statement) as key: i.e. data_array[:,0] for timeS

    sal = data_array[:,15] #practical salinity
    theta = data_array[:,14]

    #####CALCULATE GSW VARS

    z = -gsw.z_from_p(pres, latitude) #make depth positive downward
    SA = gsw.SA_from_SP(sal, pres, longitude, latitude)
    CT = gsw.CT_from_pt(SA, theta)

    #Locate end of downcast
    bottom_sample = max(z)
    bottom_index = np.where(z == bottom_sample)[0][0]

    print("Cast Depth: ", bottom_sample)

    start_index = np.where(pres>3)[0][0]
    end_index = np.where(pres>2)[0][-1]


    # Create a DataFrame and bin by depth
    df_DC = pd.DataFrame({"Depth": z[start_index:bottom_index],
                          "Absolute Salinity": SA[start_index:bottom_index],
                          "Practical Salinity": sal[start_index:bottom_index],
                          "Potential Temp": theta[start_index:bottom_index],
                          "Conservative Temp": CT[start_index:bottom_index],
                          "Pressure": pres[start_index:bottom_index],
                          "Conductivity": cond[start_index:bottom_index],
                          "Oxygen": oxy[start_index:bottom_index],
                          "Turbidity": turb2[start_index:bottom_index],
                          "Fluorescence": fluor[start_index:bottom_index]}) #turb and fluor on downcast only


    df_DC["Depth Bin"] = df_DC["Depth"] // 1  # Create bins of 1m

    #remove spikes (optional). will delete rows where there is a big spike
    df_DC = remove_spikes(df_DC)




    #Create upcast dataframe and bin by depth

    df_UC = pd.DataFrame({"Depth": z[bottom_index:end_index],
                          "Absolute Salinity": SA[bottom_index:end_index],
                          "Practical Salinity": sal[bottom_index:end_index],
                          "Potential Temp": theta[bottom_index:end_index],
                          "Conservative Temp": CT[bottom_index:end_index],
                          "Pressure": pres[bottom_index:end_index],
                          "Conductivity": cond[bottom_index:end_index],
                          "Oxygen": oxy[bottom_index:end_index],
                          "Turbidity": np.nan,
                          "Fluorescence": np.nan})


    df_UC["Depth Bin"] = df_UC["Depth"] // 1  # Create bins of 1m

    #remove spikes (optional). will delete rows where there is a big spike
    df_UC = remove_spikes(df_UC)

    # Compute average variables per bin
    binned_data_DC = df_DC.groupby("Depth Bin")[["Absolute Salinity",
                                                 "Practical Salinity",
                                                 "Potential Temp",
                                                 "Conservative Temp",
                                                 "Pressure",
                                                 "Conductivity",
                                                 "Oxygen",
                                                 "Turbidity",
                                                 "Fluorescence"]].mean() #average and combine 1m bins



    binned_data_UC = df_UC.groupby("Depth Bin")[["Absolute Salinity",
                                                  "Practical Salinity",
                                                  "Potential Temp",
                                                  "Conservative Temp",
                                                  "Pressure",
                                                  "Conductivity",
                                                  "Oxygen",
                                                  "Turbidity",
                                                  "Fluorescence"]].mean() #average and combine 1m bins

    #create a dictionary with cast-specific metadata
    stats_dict = {"Cast Number": cast_num,
                  "Latitude": latitude,
                  "Longitude": longitude,
                  "Date": date}

    #make depth bin a column not an index
    binned_data_DC = binned_data_DC.reset_index()
    binned_data_UC = binned_data_UC.reset_index()


    return binned_data_DC, binned_data_UC, stats_dict


def make_RBR_dataframe(binned_data_DC, binned_data_UC, stats_dict):

    rbr_filename = '/Users/nataliemcgee/Documents/Upernavik Project/Upernavik Data/cnv_data/RBRCTD_MB2024.mat'
    A = sio.loadmat(rbr_filename)

    #get cast number from stats dictionary for this cast
    cast_num = stats_dict["Cast Number"]

    #this is the corresponding index in the RBR file
    cast_index=int(cast_num-1)

    # Extract each variable and convert it into a nxm array: each column represents 1 of m casts with number of samples n
    # Transpose so each row is one cast
    cond_R = A['cond'].T
    sal_R = A['sal'].T #practical salinity?
    temp_R = A['temp'].T
    theta_R = A['theta'].T

    #These guys only seem to have one cast?
    pres_R = A['pres'][0].T #this one is also weirdly formatted and counts 1,2,3...
    pres_R = pres_R - 10.1325 #adjust for surface pressure

    #####CALCULATE GSW VARS

    z_R = - gsw.z_from_p(pres_R, stats_dict["Latitude"]) # make depth positive downward
    SA_R = gsw.SA_from_SP(sal_R[cast_index], pres_R, stats_dict["Longitude"], stats_dict["Latitude"])
    CT_R = gsw.CT_from_t(sal_R[cast_index], temp_R[cast_index], pres_R) #this way all arguments are the same shape, for one cast

    df_RBR = pd.DataFrame({"Depth": z_R,
                           "Absolute Salinity": SA_R,
                           "Practical Salinity": sal_R[cast_index],
                           "Potential Temp": theta_R[cast_index],
                           "Conservative Temp": CT_R,
                           "Pressure": pres_R,
                           "Conductivity": cond_R[cast_index],
                           "Oxygen": np.nan,
                           "Turbidity": np.nan,
                           "Fluorescence": np.nan})

    df_RBR["Depth Bin"] = df_RBR["Depth"] // 1

    #remove spikes (optional). will delete rows where there is a big spike
    df_RBR = remove_spikes(df_RBR)

    binned_data_RBR = df_RBR.groupby("Depth Bin")[["Absolute Salinity",
                                                   "Practical Salinity",
                                                   "Potential Temp",
                                                   "Conservative Temp",
                                                   "Pressure",
                                                   "Conductivity",
                                                   "Oxygen",
                                                   "Turbidity",
                                                   "Fluorescence"]].mean()

    binned_data_RBR = binned_data_RBR.reset_index() #make depth bin a column not an index
    binned_data_RBR = binned_data_RBR[binned_data_RBR["Depth Bin"] >= 0] #get rid of negative (above surface) rows


    return binned_data_RBR


def get_downcast_part(binned_data_DC, binned_data_UC):

    # Identify where the DC and UC are within the min error of each other
    min_error = 0.06


    depths_within_error = binned_data_DC["Depth Bin"][np.abs((binned_data_DC["Absolute Salinity"]-binned_data_UC["Absolute Salinity"])) < min_error].tolist()

    buffer_length=10
    cutoff_depth=0

    for i in range(len(depths_within_error)):
        if depths_within_error[i]+buffer_length==depths_within_error[i+buffer_length]: #10 consecutive meters (note depths are negative)
            cutoff_depth=depths_within_error[i+buffer_length]
            break

    trimmed_binned_DC = binned_data_DC[binned_data_DC["Depth Bin"] > cutoff_depth] #trims data by depth bin

    return trimmed_binned_DC, cutoff_depth




def add_upcast_patch(binned_data_DC, binned_data_UC):

    #Get trimmed binned downcast part
    trimmed_binned_DC, cutoff_depth  = get_downcast_part(binned_data_DC, binned_data_UC)

    #Get trimmed binned upcast patch
    UC_patch = binned_data_UC[binned_data_UC["Depth Bin"] <= cutoff_depth]

    #Stick them together
    uc_patched_data = pd.concat([trimmed_binned_DC, UC_patch], ignore_index=True)
    uc_patched_data = uc_patched_data.sort_values("Depth Bin", ascending = True).reset_index(drop=True) #reorder by depth, with shallowest first

    return uc_patched_data





def add_RBR_patch(binned_data_DC, binned_data_UC, stats_dict):

    #Get trimmed binned downcast part
    trimmed_binned_DC, cutoff_depth = get_downcast_part(binned_data_DC, binned_data_UC)

    #fill with NaNs if no RBR
    if stats_dict["Cast Number"] in [1, 2, 3, 5]:
        depths = np.arange(-9.0, cutoff_depth, 1.0)

        RBR_patch = pd.DataFrame({
            "Depth Bin": depths,
            "Absolute Salinity": np.nan,
            "Practical Salinity": np.nan,
            "Potential Temp": np.nan,
            "Conservative Temp": np.nan,
            "Pressure": np.nan,
            "Conductivity": np.nan,
            "Oxygen": np.nan})


    else:

        RBR_patch = make_RBR_dataframe(binned_data_DC, binned_data_UC, stats_dict)

        RBR_patch = RBR_patch[RBR_patch["Depth Bin"] <= cutoff_depth] #trims data by depth bin

    rbr_patched_data = pd.concat([trimmed_binned_DC, RBR_patch], ignore_index=True)
    rbr_patched_data = rbr_patched_data.sort_values("Depth Bin", ascending = True).reset_index(drop=True) #reorder by depth, with shallowest first

    return rbr_patched_data



# def add_other_vars(dataframe, binned_data_DC, stats_dict):

#     #Add turbidity and fluorescence: keep whole downcast

#     #get rid of everything from the whole downcast except depth bin, turbidity, and fluorescence
#     turb_fluor_df = binned_data_DC.drop(columns=["Absolute Salinity",
#                                                   "Practical Salinity",
#                                                   "Potential Temp",
#                                                   "Conservative Temp",
#                                                   "Pressure",
#                                                   "Conductivity",
#                                                   "Oxygen"])


#     #Recalculate absolute salinity and conservative temperature from patched variables

#     SA = gsw.SA_from_SP(dataframe["Practical Salinity"], dataframe["Pressure"], stats_dict["Longitude"], stats_dict["Latitude"])
#     CT = gsw.CT_from_pt(SA, dataframe["Potential Temp"])

#     #replace the existing columns with the new ones
#     dataframe["Absolute Salinity"]=SA
#     dataframe["Conservative Temp"]=CT
#     dataframe["Turbidity"]=turb_fluor_df["Turbidity"]
#     dataframe["Fluorescence"]=turb_fluor_df["Fluorescence"]

#     final_merged_df = dataframe

#     return final_merged_df

def add_other_vars(dataframe, binned_data_DC, stats_dict):
    # Only keep depth, turbidity, fluorescence from downcast
    turb_fluor_df = binned_data_DC[["Depth Bin", "Turbidity", "Fluorescence"]].copy()

    # Merge both dataframes on Depth Bin
    merged_df = pd.merge(dataframe, turb_fluor_df, on="Depth Bin", how="outer", suffixes=('', '_new'))

    # Replace turbidity and fluorescence if available
    for var in ["Turbidity", "Fluorescence"]:
        merged_df[var] = merged_df[f"{var}_new"].combine_first(merged_df[var])
        merged_df = merged_df.drop(columns=[f"{var}_new"])

    # Recalculate SA and CT
    SA = pd.Series(index=merged_df.index, dtype=float)
    CT = pd.Series(index=merged_df.index, dtype=float)

    valid = merged_df[["Practical Salinity", "Pressure", "Potential Temp"]].notnull().all(axis=1)
    SA[valid] = gsw.SA_from_SP(merged_df.loc[valid, "Practical Salinity"],
                               merged_df.loc[valid, "Pressure"],
                               stats_dict["Longitude"],
                               stats_dict["Latitude"])
    CT[valid] = gsw.CT_from_pt(SA[valid], merged_df.loc[valid, "Potential Temp"])

    merged_df["Absolute Salinity"] = SA
    merged_df["Conservative Temp"] = CT

    return merged_df



"""# Filenames and Dates"""

from datetime import datetime

filenames = ["2024-07-31T082954_SBE0251108_1.cnv", "2024-07-31T115713_SBE0251108_2.cnv", "2024-07-31T161825_SBE0251108_3.cnv",
    "2024-07-31T204110_SBE0251108_4.cnv", "2024-07-31T224744_SBE0251108_5.cnv", "2024-08-01T084101_SBE0251108_6.cnv",
    "2024-08-01T153527_SBE0251108_7.cnv", "2024-08-01T201934_SBE0251108_8.cnv", "2024-08-01T233200_SBE0251108_9.cnv",
    "2024-08-02T084239_SBE0251108_10.cnv", "2024-08-02T103912_SBE0251108_11.cnv", "2024-08-02T124148_SBE0251108_12.cnv",
    "2024-08-02T144354_SBE0251108_13.cnv", "2024-08-02T162230_SBE0251108_14.cnv", "2024-08-02T181153_SBE0251108_15.cnv",
    "2024-08-02T193643_SBE0251108_16.cnv", "2024-08-02T212325_SBE0251108_17.cnv", "2024-08-02T225334_SBE0251108_18.cnv",
    "2024-08-03T001129_SBE0251108_19.cnv", "2024-08-03T092012_SBE0251108_20.cnv", "2024-08-03T120656_SBE0251108_21.cnv",
    "2024-08-03T145243_SBE0251108_22.cnv", "2024-08-03T170903_SBE0251108_23.cnv", "2024-08-03T200331_SBE0251108_24.cnv",
    "2024-08-03T213706_SBE0251108_25.cnv", "2024-08-04T081650_SBE0251108_26.cnv", "2024-08-04T104302_SBE0251108_27.cnv",
    "2024-08-04T123536_SBE0251108_28.cnv", "2024-08-04T14440_SBE0251108_29.cnv", "2024-08-04T171848_SBE0251108_30.cnv",
    "2024-08-04T201651_SBE0251108_31.cnv", "2024-08-04T220733_SBE0251108_32.cnv", "2024-08-04T234506_SBE0251108_33.cnv",
    "2024-08-05T091018_SBE0251108_34.cnv", "2024-08-05T114331_SBE0251108_35.cnv", "2024-08-05T134522_SBE0251108_36.cnv",
    "2024-08-05T165955_SBE0251108_37.cnv", "2024-08-05T202014_SBE0251108_38.cnv", "2024-08-06T113756_SBE0251108_39.cnv",
    "2024-08-06T154243_SBE0251108_40.cnv", "2024-08-06T185548_SBE0251108_41.cnv", "2024-08-07T113257_SBE0251108_42.cnv",
    "2024-08-07T151251_SBE0251108_43.cnv", "2024-08-08T122239_SBE0251108_44.cnv", "2024-08-08T215139_SBE0251108_45.cnv",
    "2024-08-08T234107_SBE0251108_46.cnv", "2024-08-09T140610_SBE0251108_47.cnv", "2024-08-10T090448_SBE0251108_48.cnv",
    "2024-08-10T102543_SBE0251108_49.cnv", "2024-08-10T120504_SBE0251108_50.cnv", "2024-08-10T140748_SBE0251108_51.cnv",
    "2024-08-10T154233_SBE0251108_52.cnv", "2024-08-10T174102_SBE0251108_53.cnv", "2024-08-10T203048_SBE0251108_54.cnv",
    "2024-08-11T090624_SBE0251108_55.cnv", "2024-08-11T114648_SBE0251108_56.cnv"]

# Extract date from filename and reformat to "DD-Mmm-YY"
extracted_dates = [datetime.strptime(f.split("T")[0], "%Y-%m-%d").strftime("%Y-%m-%d") for f in filenames]

print(extracted_dates)

"""# Write to NetCDF Function"""

import os
from netCDF4 import Dataset
from datetime import datetime

def write_to_netCDF(df, stats_dict, filename, flag_type):
    """
    Appends a CTD cast (df + stats_dict) to a NetCDF file using VLEN arrays
    to handle varying depths per cast.

    Parameters:
        df (pd.DataFrame): Profile data (depth, temperatures, salinities, etc.)
        stats_dict (dict): Metadata with keys like 'latitude', 'longitude', 'date', 'cast_number'
        filename (str): Output NetCDF filename
    """
    # Ensure consistent column order and float dtype
    df = df.astype('float32').reset_index(drop=True)

    variables = ['Depth Bin',
                 "Absolute Salinity",
                 "Practical Salinity",
                 "Potential Temp",
                 "Conservative Temp",
                 "Pressure",
                 "Conductivity",
                 "Oxygen",
                 "Turbidity",
                 "Fluorescence"]

    # create the NetCDF file if it doesnt exist yet
    if not os.path.exists(filename):
        ncfile = Dataset(filename, 'w', format='NETCDF4')
        ncfile.createDimension('cast', None)  # Unlimited dimension

        # Create metadata variables
        ncfile.createVariable('Latitude', 'f4', ('cast',))
        ncfile.createVariable('Longitude', 'f4', ('cast',))
        ncfile.createVariable('Cast_Number', 'i4', ('cast',))
        ncfile.createVariable('Date', 'i8', ('cast',))  #saves date as timestamp
        ncfile.createVariable('Flag', 'i8', ('cast',))

        # Create VLEN type
        vlen_float = ncfile.createVLType(np.float32, 'vlen_float')

        # Create profile variables
        for var in variables:
            ncfile.createVariable(var, vlen_float, ('cast',))

        cast_index = 0

    # if the file already exists
    else:
        ncfile = Dataset(filename, 'a') #open file in append mode
        cast_index = len(ncfile.dimensions['cast']) #how many casts are already in it

    # write metadata
    ncfile['Latitude'][cast_index] = stats_dict['Latitude']
    ncfile['Longitude'][cast_index] = stats_dict['Longitude']
    ncfile['Cast_Number'][cast_index] = stats_dict['Cast Number']
    date = pd.to_datetime(stats_dict['Date'])
    ncfile['Date'][cast_index] = int(date.timestamp()) #put the date in the right format
    ncfile['Flag'][cast_index] = flag_type


    # write each profile variable (VLEN arrays)
    for var in variables:
        ncfile[var][cast_index] = df[var].to_numpy(dtype='float32')

    ncfile.close()

"""# Special Case Functions"""

def special_case_cast_1(netCDF_filename, treatment_type):

    binned_data_DC, binned_data_UC, stats_dict = make_UC_and_DC_dataframes("/Users/nataliemcgee/Documents/Upernavik Project/Upernavik Data/cnv_data/2024-07-31T082954_SBE0251108_1.cnv",
                                                                               extracted_dates[0])

    if treatment_type == "rbr": #its all nans make everything nans for the whole depth

        #cast 1 depth is 803 m
        depths = np.arange(0.0, 804.0, 1.0)

        cast1_df = pd.DataFrame({
            "Depth Bin": depths,
            "Absolute Salinity": np.nan,
            "Practical Salinity": np.nan,
            "Potential Temp": np.nan,
            "Conservative Temp": np.nan,
            "Pressure": np.nan,
            "Conductivity": np.nan,
            "Oxygen": np.nan,
            "Turbidity": np.nan,
            "Fluorescence": np.nan})


    if treatment_type == "seabird": #we have a little bit of upcast but make the top nans then stick it on

        #cast 1 upcast ends at 558 m
        depths = np.arange(0.0, 558.0, 1.0)

        #make some nans to put the top
        nan_patch = pd.DataFrame({
            "Depth Bin": depths,
            "Absolute Salinity": np.nan,
            "Practical Salinity": np.nan,
            "Potential Temp": np.nan,
            "Conservative Temp": np.nan,
            "Pressure": np.nan,
            "Conductivity": np.nan,
            "Oxygen": np.nan,
            "Turbidity": np.nan,
            "Fluorescence": np.nan})

        cast1_df = pd.concat([nan_patch, binned_data_UC], ignore_index=True) #stick em together
        cast1_df = cast1_df.sort_values("Depth Bin", ascending = True).reset_index(drop=True) #reorder by depth, with shallowest first

    #line up DC turb and fluor, and merge
    cast1_df = cast1_df.merge(binned_data_DC[["Depth Bin", "Turbidity", "Fluorescence"]],
                                            on="Depth Bin",
                                            how="left",
                                            suffixes=('', '_from_DC'))


    #replace original columns:
    cast1_df["Turbidity"] = cast1_df["Turbidity_from_DC"]
    cast1_df["Fluorescence"] = cast1_df["Fluorescence_from_DC"]


    #drop the extra columns:
    cast1_df = cast1_df.drop(columns=["Turbidity_from_DC", "Fluorescence_from_DC"])

    #write to file
    write_to_netCDF(cast1_df, stats_dict, netCDF_filename, flag_type=2)


def special_case_cast_10(netCDF_filename, treatment_type):

    binned_data_DC, binned_data_UC, stats_dict = make_UC_and_DC_dataframes("/Users/nataliemcgee/Documents/Upernavik Project/Upernavik Data/cnv_data/2024-08-02T084239_SBE0251108_10.cnv",
                                                                               extracted_dates[9])

    if treatment_type == "rbr":

        #just take whole RBR cast
        binned_data_RBR = make_RBR_dataframe(binned_data_DC, binned_data_UC, stats_dict)

        #line up DC turb and fluor, and merge
        binned_data_RBR = binned_data_RBR.merge(binned_data_DC[["Depth Bin", "Turbidity", "Fluorescence"]],
                                                on="Depth Bin",
                                                how="left",
                                                suffixes=('', '_from_DC'))

        #replace original columns:
        binned_data_RBR["Turbidity"] = binned_data_RBR["Turbidity_from_DC"]
        binned_data_RBR["Fluorescence"] = binned_data_RBR["Fluorescence_from_DC"]

        #drop the extra columns:
        binned_data_RBR = binned_data_RBR.drop(columns=["Turbidity_from_DC", "Fluorescence_from_DC"])

        cast10_df = binned_data_RBR


    if treatment_type == "seabird":

        #none of the data except depth, pressure, turbidity, fluorescence is reliable tbh
        binned_data_DC["Absolute Salinity"] = np.nan
        binned_data_DC["Practical Salinity"] = np.nan
        binned_data_DC["Potential Temp"] = np.nan
        binned_data_DC["Conservative Temp"] = np.nan
        binned_data_DC["Conductivity"] = np.nan
        binned_data_DC["Oxygen"] = np.nan

        #fluor and turb should still be in the binned_data_dc df...

        cast10_df = binned_data_DC

    write_to_netCDF(cast10_df, stats_dict, netCDF_filename, flag_type = 3)

"""# Create Dataset Functions"""

def create_RBR_patch_dataset(patch_casts, as_is_casts):

    netCDF_filename="/Users/nataliemcgee/Documents/Upernavik Project/Upernavik Data/rbr_patch_dataset_new.nc"

    #Create RBR patch for the affected casts
    patched_filename_indeces = [item-1 for item in patch_casts]


    for index in patched_filename_indeces:

        if index+1 == 1 :
            special_case_cast_1(netCDF_filename, "rbr") #makes it all nans except depth, pressure, turb, and fluor
            print("Cast completed:", 1)
            continue

        if index+1 == 10 :
            special_case_cast_10(netCDF_filename, "rbr") #puts in whole rbr and DC turb and fluor
            print("Cast completed:", 10)
            continue

        binned_data_DC, binned_data_UC, stats_dict = make_UC_and_DC_dataframes(f"/Users/nataliemcgee/Documents/Upernavik Project/Upernavik Data/cnv_data/{filenames[index]}",
                                                                               extracted_dates[index])

        trimmed_binned_DC, cutoff_depth = get_downcast_part(binned_data_DC, binned_data_UC)

        print("Cutoff Depth:", cutoff_depth)

        rbr_patched_data = add_RBR_patch(binned_data_DC, binned_data_UC, stats_dict)

        final_merged_df = add_other_vars(rbr_patched_data, binned_data_DC, stats_dict)

        #WRITE THE FINAL MERGED DF TO A NETCDF. Each df is its own cast
        write_to_netCDF(final_merged_df, stats_dict, netCDF_filename, flag_type = 1)

        print("Cast completed:", index+1)



    #Now add the as-is casts
    filename_indeces = [item-1 for item in as_is_casts]

    for index in filename_indeces:

        binned_data_DC, binned_data_UC, stats_dict = make_UC_and_DC_dataframes(f"/Users/nataliemcgee/Documents/Upernavik Project/Upernavik Data/cnv_data/{filenames[index]}",
                                                                               extracted_dates[index])
        #WRITE THE FINAL MERGED DF TO A NETCDF. Each df is its own cast
        write_to_netCDF(binned_data_DC, stats_dict, netCDF_filename, flag_type = 0)

        print("Cast completed:", index+1)

    print("NetCDF File saved! Pathname:", netCDF_filename)



def create_UC_patch_dataset(patch_casts, as_is_casts):

    netCDF_filename="/Users/nataliemcgee/Documents/Upernavik Project/Upernavik Data/uc_patch_dataset_new.nc"

    #Create UC patch for the affected casts
    patched_filename_indeces = [item-1 for item in patch_casts]

    for index in patched_filename_indeces:

        if index+1 == 1 :
            special_case_cast_1(netCDF_filename, "seabird") #puts in upcast + DC turb and fluor
            print("Cast completed:", 1)
            continue

        if index+1 == 10 :
            special_case_cast_10(netCDF_filename, "seabird") #makes it all nans except depth, pressure, turb, and fluor
            print("Cast completed:", 10)
            continue

        binned_data_DC, binned_data_UC, stats_dict = make_UC_and_DC_dataframes(f"/Users/nataliemcgee/Documents/Upernavik Project/Upernavik Data/cnv_data/{filenames[index]}",
                                                                               extracted_dates[index])
        trimmed_binned_DC, cutoff_depth = get_downcast_part(binned_data_DC, binned_data_UC)

        uc_patched_data = add_upcast_patch(binned_data_DC, binned_data_UC)

        final_merged_df = add_other_vars(uc_patched_data, binned_data_DC, stats_dict)

        #WRITE THE FINAL MERGED DF TO A NETCDF. Each df is its own cast
        write_to_netCDF(final_merged_df, stats_dict, netCDF_filename, flag_type = 1)

        print("Cast completed:", index+1)



    #Now add the as-is casts
    filename_indeces = [item-1 for item in as_is_casts]

    for index in filename_indeces:

        binned_data_DC, binned_data_UC, stats_dict = make_UC_and_DC_dataframes(f"/Users/nataliemcgee/Documents/Upernavik Project/Upernavik Data/cnv_data/{filenames[index]}",
                                                                               extracted_dates[index])

        #WRITE THE FINAL MERGED DF TO A NETCDF. Each df is its own cast
        write_to_netCDF(binned_data_DC, stats_dict, netCDF_filename, flag_type = 0)

        print("Cast completed:", index+1)

    print("NetCDF File saved! Pathname:", netCDF_filename)



def create_downcast_only_dataset(patch_casts, as_is_casts):

    netCDF_filename="/Users/nataliemcgee/Documents/Upernavik Project/Upernavik Data/dc_only_dataset_new.nc"

    #Cut off surface section of the affected casts
    patched_filename_indeces = [item-1 for item in patch_casts]

    for index in patched_filename_indeces:

        if index+1 == 1 :
            special_case_cast_1(netCDF_filename, "rbr") #rbr argument makes it all nans rather than putting in the upcast
            print("Cast completed:", 1)
            continue

        if index+1 == 10 :
            special_case_cast_10(netCDF_filename, "seabird") #makes it all nans except depth, pressure, turb, and fluor
            print("Cast completed:", 10)
            continue

        binned_data_DC, binned_data_UC, stats_dict = make_UC_and_DC_dataframes(f"/Users/nataliemcgee/Documents/Upernavik Project/Upernavik Data/cnv_data/{filenames[index]}",
                                                                               extracted_dates[index])
        
        trimmed_binned_DC, cutoff_depth = get_downcast_part(binned_data_DC, binned_data_UC)
        
        final_merged_df = add_other_vars(trimmed_binned_DC, binned_data_DC, stats_dict)

        #WRITE THE FINAL MERGED DF TO A NETCDF. Each df is its own cast
        write_to_netCDF(final_merged_df, stats_dict, netCDF_filename, flag_type = 1)

        print("Cast completed:", index+1)



    #Now add the as-is casts
    filename_indeces = [item-1 for item in as_is_casts]

    for index in filename_indeces:

        binned_data_DC, binned_data_UC, stats_dict = make_UC_and_DC_dataframes(f"/Users/nataliemcgee/Documents/Upernavik Project/Upernavik Data/cnv_data/{filenames[index]}",
                                                                               extracted_dates[index])

        #WRITE THE FINAL MERGED DF TO A NETCDF. Each df is its own cast
        write_to_netCDF(binned_data_DC, stats_dict, netCDF_filename, flag_type = 0)

        print("Cast completed:", index+1)

    print("NetCDF File saved! Pathname:", netCDF_filename)



def create_upcast_only_dataset(patch_casts, as_is_casts):

    netCDF_filename="/Users/nataliemcgee/Documents/Upernavik Project/Upernavik Data/uc_only_dataset_new.nc"

    #Get upcast df for the affected casts
    patched_filename_indeces = [item-1 for item in patch_casts]

    for index in patched_filename_indeces:

        if index+1 == 1 :
            special_case_cast_1(netCDF_filename, "seabird") #puts in upcast + DC turb and fluor
            print("Cast completed:", 1)
            continue

        if index+1 == 10 :
            special_case_cast_10(netCDF_filename, "seabird") #makes it all nans except depth, pressure, turb, and fluor
            print("Cast completed:", 10)
            continue

        binned_data_DC, binned_data_UC, stats_dict = make_UC_and_DC_dataframes(f"/Users/nataliemcgee/Documents/Upernavik Project/Upernavik Data/cnv_data/{filenames[index]}",
                                                                               extracted_dates[index])
        
        final_merged_df = add_other_vars(binned_data_UC, binned_data_DC, stats_dict)
        
        #WRITE THE FINAL MERGED DF TO A NETCDF. Each df is its own cast
        write_to_netCDF(final_merged_df, stats_dict, netCDF_filename, flag_type = 1)

        print("Cast completed:", index+1)



    #Now add the as-is casts
    filename_indeces = [item-1 for item in as_is_casts]

    for index in filename_indeces:

        binned_data_DC, binned_data_UC, stats_dict = make_UC_and_DC_dataframes(f"/Users/nataliemcgee/Documents/Upernavik Project/Upernavik Data/cnv_data/{filenames[index]}",
                                                                               extracted_dates[index])

        #WRITE THE FINAL MERGED DF TO A NETCDF. Each df is its own cast
        write_to_netCDF(binned_data_DC, stats_dict, netCDF_filename, flag_type = 0)

        print("Cast completed:", index+1)

    print("NetCDF File saved! Pathname:", netCDF_filename)


def create_RBR_only_dataset(patch_casts, as_is_casts):

    netCDF_filename="/Users/nataliemcgee/Documents/Upernavik Project/Upernavik Data/rbr_only_dataset_new.nc"

    #Get RBR data for affected casts
    patched_filename_indeces = [item-1 for item in patch_casts]

    for index in patched_filename_indeces:

        if index+1 == 1 :
            special_case_cast_1(netCDF_filename, "rbr") #all nans except depth, pressure, turb, and fluor
            print("Cast completed:", 1)
            continue

        if index+1 == 10 :
            special_case_cast_10(netCDF_filename, "rbr") #puts in whole rbr and DC turb and fluor
            print("Cast completed:", 10)
            continue

        binned_data_DC, binned_data_UC, stats_dict = make_UC_and_DC_dataframes(f"/Users/nataliemcgee/Documents/Upernavik Project/Upernavik Data/cnv_data/{filenames[index]}",
                                                                               extracted_dates[index])

        binned_data_RBR = make_RBR_dataframe(binned_data_DC, binned_data_UC, stats_dict)

        final_merged_df = add_other_vars(binned_data_RBR, binned_data_DC, stats_dict)


        #WRITE THE FINAL MERGED DF TO A NETCDF. Each df is its own cast
        write_to_netCDF(final_merged_df, stats_dict, netCDF_filename, flag_type = 1)

        print("Cast completed:", index+1)



    #Now add the as-is casts
    filename_indeces = [item-1 for item in as_is_casts]

    for index in filename_indeces:

        binned_data_DC, binned_data_UC, stats_dict = make_UC_and_DC_dataframes(f"/Users/nataliemcgee/Documents/Upernavik Project/Upernavik Data/cnv_data/{filenames[index]}",
                                                                               extracted_dates[index])

        #WRITE THE FINAL MERGED DF TO A NETCDF. Each df is its own cast
        write_to_netCDF(binned_data_DC, stats_dict, netCDF_filename, flag_type = 0)

        print("Cast completed:", index+1)

    print("NetCDF File saved! Pathname:", netCDF_filename)

"""# This is the only cell you need to use"""

import warnings
warnings.filterwarnings("ignore") #runtime warnings from GSW

problem_casts = np.arange(1, 13, 1) #for patch, or for downcast only, upcast only

casts_good_as_is = np.arange(13, 57, 1)

#remember to delete existing files or rename to avoid adding to them,
#these functions will just add casts to the same file rather than overwrite

create_RBR_patch_dataset(problem_casts, casts_good_as_is)

create_UC_patch_dataset(problem_casts, casts_good_as_is)

create_upcast_only_dataset(problem_casts, casts_good_as_is)

create_downcast_only_dataset(problem_casts, casts_good_as_is)

create_RBR_only_dataset(problem_casts, casts_good_as_is)

